"""Build the distributable bundle other sites link to: python3 scripts/build_dist.py [--check].

Concatenates fonts.css + tokens.css + base.css + components.css into one stylesheet and copies
the token export and icon sprite next to it. Two channels are written from the same content:

  dist/tiansight.css        latest — a consumer linking this follows every push
  dist/tiansight-<ver>.css  pinned — frozen at the version in brand/VERSION

Font urls are rewritten to ../brand/fonts/ so the bundle resolves against the repository root
whether it is served by GitHub Pages or a repository CDN. No timestamp is written, so the output
is deterministic and scripts/check.py can verify it is in step with the sources.
"""
from pathlib import Path
import shutil
import sys

root = Path(__file__).resolve().parents[1]
brand = root / 'brand'
dist = root / 'dist'
PARTS = ('fonts.css', 'tokens.css', 'base.css', 'components.css')


def render():
    version = (brand / 'VERSION').read_text().strip()
    head = (f'/*! Tiansight 侍天 design system {version} — one-file bundle.\n'
            f' * Source: brand/{", brand/".join(PARTS)} · generated by scripts/build_dist.py, do not edit.\n'
            ' * Webfont files are not bundled; faces fall back to local serifs until brand/fonts/ is filled.\n'
            ' * Tokens as data: dist/tokens.json · icon sprite: dist/icons.svg · changelog: CHANGELOG.md\n'
            ' */\n')
    body = []
    for part in PARTS:
        css = (brand / part).read_text().replace('url("fonts/', 'url("../brand/fonts/')
        body.append(f'\n/* ══ brand/{part} ══════════════════════════════════════════ */\n{css.rstrip()}\n')
    return version, head + ''.join(body)


def build(check=False):
    version, css = render()
    files = {dist / 'tiansight.css': css,
             dist / f'tiansight-{version}.css': css,
             dist / 'tokens.json': (brand / 'tokens.json').read_text(),
             dist / 'icons.svg': (brand / 'icons.svg').read_text()}
    stale = [p for p, text in files.items() if not p.is_file() or p.read_text() != text]
    if check:
        if stale:
            print('stale: ' + ', '.join(sorted(p.relative_to(root).as_posix() for p in stale)) +
                  ' — run python3 scripts/build_dist.py')
            return 1
        print(f'dist/ is up to date ({version})')
        return 0
    dist.mkdir(exist_ok=True)
    for path, text in files.items():
        path.write_text(text)
    for old in dist.glob('tiansight-v*.css'):
        if old.name != f'tiansight-{version}.css':
            print(f'note: {old.name} is an older pinned channel, kept for consumers linking it')
    print(f'wrote dist/tiansight.css and dist/tiansight-{version}.css ({len(css):,} bytes), tokens.json, icons.svg')
    return 0


if __name__ == '__main__':
    sys.exit(build('--check' in sys.argv))
