"""Build the co-founder profile pages from people/profiles.json.

    python3 scripts/build_profiles.py            # write the pages
    python3 scripts/build_profiles.py --check    # fail if a page on disk is stale

Outputs, per profile in the library:
    people/profile-<id>.html      完整版 — seven A4 pages, print to PDF as-is
    people/profile-<id>-1p.html   一页版 — one A4 page
and one index, people/profiles.html, which lists the library by category.

Every entry in profiles.json carries a category from the declared vocabulary, and every number
carries a source id and an evidence grade. The build refuses to run when a profile shows more
than three auxiliary titles, when a number has no source, or when a category or source is not
declared — the same discipline the report system applies to client data.
"""
from pathlib import Path
import html as H
import json
import sys

root = Path(__file__).resolve().parents[1]
data_path = root / 'people' / 'profiles.json'
MAX_AUX = 3


def esc(text):
    return H.escape(str(text), quote=True)


def load():
    return json.loads(data_path.read_text(encoding='utf-8'))


# ── validation ──────────────────────────────────────────────
def numbers(profile, unique=False):
    """Every number the pages print. With unique, one row per distinct claim for the source table."""
    out = list(profile.get('figures', []))
    for case in profile.get('cases', []):
        out += case.get('results', [])
    out += list(profile.get('trainings', []))
    if not unique:
        return out
    seen, rows = set(), []
    for entry in out:
        label = entry.get('metric') or entry.get('zh') or entry.get('title', '')
        value = entry.get('value') or entry.get('scale') or ''
        key = (label, ''.join(ch for ch in value if ch.isalnum()))
        if key in seen:
            continue
        seen.add(key)
        rows.append(entry)
    return rows


def validate(data):
    problems = []
    categories, sources = data['categories'], data['sources']
    for profile in data['profiles']:
        who = profile['id']
        shown = [t for t in profile['titles_aux'] if t['show']]
        if len(shown) > MAX_AUX:
            problems.append(f'{who}: {len(shown)} auxiliary titles shown, at most {MAX_AUX}')
        if not profile.get('title_main'):
            problems.append(f'{who}: no main title')
        for entry in numbers(profile):
            if entry.get('grade') not in data['grades']:
                problems.append(f'{who}/{entry.get("id")}: grade {entry.get("grade")} not declared')
            if entry.get('source') not in sources:
                problems.append(f'{who}/{entry.get("id")}: source {entry.get("source")} not declared')
        typed = (profile.get('figures', []) + profile.get('principles', []) + profile.get('capabilities', [])
                 + profile.get('brands', []) + profile.get('services', []) + profile.get('roles', [])
                 + profile.get('education', []) + profile.get('trainings', []) + profile.get('cases', []))
        cap_ids = {c['id'] for c in profile['capabilities']}
        for case in profile['cases']:
            for cid in case.get('capabilities', []):
                if cid not in cap_ids:
                    problems.append(f'{who}/{case["id"]}: capability {cid} not in this profile')
        for entry in typed:
            if entry.get('type') not in categories:
                problems.append(f'{who}/{entry.get("id")}: category {entry.get("type")} not in the vocabulary')
        if profile.get('source') not in sources:
            problems.append(f'{who}: profile source {profile.get("source")} not declared')
    return problems


# ── fragments ───────────────────────────────────────────────
def head(title, css_depth='../'):
    return f'''<!doctype html>
<html lang="zh-Hans">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<link rel="stylesheet" href="{css_depth}brand/fonts.css">
<link rel="stylesheet" href="{css_depth}brand/tokens.css">
<link rel="stylesheet" href="{css_depth}brand/base.css">
<link rel="stylesheet" href="{css_depth}brand/components.css">
<link rel="stylesheet" href="profile.css">
</head>
<body>
<!-- Generated by scripts/build_profiles.py from people/profiles.json. Edit the data, not this file. -->
<a class="ts-skip" href="#top">跳到正文</a>'''


def shell_head(profile, kind, other_href, other_label):
    aux = ' · '.join(t['zh'] for t in profile['titles_aux'] if t['show'])
    return f'''<div class="shell-head">
  <div class="ts-container" style="padding-block:var(--space-5)">
    <div class="ts-heading">
      <span class="ts-caption">Co-founder profile · {esc(profile["en"])} · {esc(kind)}</span>
      <p class="ts-sub" style="margin:0">{esc(profile["title_main"])} · {esc(aux)}　—　打印即得 A4 PDF。<a href="{esc(other_href)}">{esc(other_label)}</a> · <a href="profiles.html">履历库</a></p>
    </div>
  </div>
</div>'''


def page_foot(profile, no, total, tail):
    return (f'<div class="page-foot"><span>侍天 Tiansight · A Member of the Table AI Alliance</span>'
            f'<span>{esc(tail)}</span><span class="no">{no:02d} / {total:02d}</span></div>')


def figure_block(fig, dark):
    unit = f'<small>{esc(fig["unit"])}</small>' if fig.get('unit') else ''
    return (f'<div class="fig"><span class="v">{esc(fig["value"])}{unit}</span>'
            f'<span class="l">{esc(fig["label"])}</span><span class="n">{esc(fig["zh"])}</span></div>')


def cover(profile, data, total):
    aux = [t for t in profile['titles_aux'] if t['show']][:MAX_AUX]
    aux_html = ''.join(f'<span>{esc(t["zh"])}</span>' for t in aux)
    figs = ''.join(figure_block(f, True) for f in profile['figures'])
    photo = root / 'people' / profile['photo']
    portrait = (f'<img src="{esc(profile["photo"])}" alt="{esc(profile["name"])}">' if photo.is_file()
                else f'<span class="placeholder">肖像待补<br>{esc(profile["photo"])}</span>')
    return f'''<section class="page cover ts-ground-charcoal" id="cover">
  <div class="ts-compass" aria-hidden="true" style="--compass-size:165mm;left:64%;top:32%">
    <svg viewBox="0 0 600 600" fill="none" stroke="currentColor" stroke-width="1">
      <circle cx="300" cy="300" r="290"/><circle cx="300" cy="300" r="230"/><circle cx="300" cy="300" r="150"/><circle cx="300" cy="300" r="6"/>
      <path d="M300 0v600M0 300h600"/>
    </svg>
  </div>
  <div class="cover-top">
    <span class="ts-caption">侍天 Tiansight ｜ A Member of the Table AI Alliance</span>
    <span class="ts-caption">{esc(data["version"])} · {esc(data["issued"])}</span>
  </div>
  <div class="cover-body">
    <div>
      <span class="domain">{esc(profile["domain"])}</span>
      <h1>{esc(profile["name"])}</h1>
      <span class="en-name">{esc(profile["en"])}</span>
      <div class="titles">
        <span class="main">{esc(profile["title_main"])}</span>
        <div class="aux" data-aux-slot>{aux_html}</div>
      </div>
      <p class="lede">{esc(profile["lede"])}</p>
      <p class="quote">「{esc(profile["quote"])}」</p>
    </div>
    <div>
      <div class="portrait">{portrait}</div>
      <div class="figures">{figs}</div>
    </div>
  </div>
  <div class="cover-end">
    <div class="keywords">{esc(profile["keywords"])}</div>
    {page_foot(profile, 1, total, profile["domain_zh"])}
  </div>
</section>'''


def page_profile(profile, total):
    prose = ''.join(f'<p>{esc(p)}</p>' for p in profile['summary'])
    principles = ''.join(
        f'<div class="block"><span class="ts-caption">0{i}</span><h3>{esc(p["title"])}</h3><p>{esc(p["body"])}</p></div>'
        for i, p in enumerate(profile['principles'], 1))
    rows = ''.join(
        f'<div class="row"><span class="when">{esc(r.get("period", ""))}</span>'
        f'<div class="what"><h3>{esc(r["title"])}</h3> <span class="org">{esc(r["org"])}</span>'
        + (f'<p>{esc(r["note"])}</p>' if r.get('note') else '') + '</div></div>'
        for r in profile.get('roles', []))
    extra = profile.get('education', []) + profile.get('trainings', [])
    extra_rows = ''.join(
        f'<div class="row"><span class="when">{esc(e.get("period", "") or e.get("scale", ""))}</span>'
        f'<div class="what"><h3>{esc(e["title"])}</h3> <span class="org">{esc(e.get("org", ""))}</span>'
        + (f'<p>{esc(e.get("region") or e.get("role") or "")}</p>' if (e.get('region') or e.get('role')) else '')
        + '</div></div>'
        for e in extra)
    return f'''<section class="page" id="profile">
  <div class="page-head">
    <div><span class="ts-caption">Profile</span><h2>个人简介</h2></div>
    <span class="meta">{esc(profile["en"])}</span>
  </div>
  <div class="prose">{prose}</div>
  <div>
    <span class="ts-caption">Operating principles · 全案原则</span>
    <div class="cards-3" style="margin-top:3mm">{principles}</div>
  </div>
  <div>
    <span class="ts-caption">Roles · 任职经历</span>
    <div class="timeline" style="margin-top:3mm">{rows}</div>
  </div>
  <div>
    <span class="ts-caption">Education and training · 教育与培训</span>
    <div class="timeline" style="margin-top:3mm">{extra_rows}</div>
  </div>
  {page_foot(profile, 2, total, "个人简介")}
</section>'''


def page_portfolio(profile, total):
    if profile.get('brands'):
        caption, heading = 'Brand portfolio', '服务覆盖'
        groups = ''.join(
            f'<div class="group"><h3>{esc(b["group"])}</h3><p>{esc("、".join(b["items"]))}</p></div>'
            for b in profile['brands'])
        lede = '深入全案服务中国超过 100 个品牌，中国餐饮排行 TOP50 占到 60%。'
    else:
        caption, heading = 'Service portfolio', '服务覆盖'
        groups = ''.join(
            f'<div class="group"><h3>{esc(s["group"])}</h3><p>{esc(s["body"])}</p></div>'
            for s in profile['services'])
        lede = '面向高净值人群、家族办公室、顶奢品牌、政府机构、顶尖学府与企业组织，提供战略、教育、品牌、资产管理与 AI 工程一体化服务。'
    caps = ''.join(
        f'<div class="cap"><span class="n">0{i}</span><h3>{esc(c["title"])}</h3></div>'
        for i, c in enumerate(profile['capabilities'], 1))
    return f'''<section class="page" id="portfolio">
  <div class="page-head">
    <div><span class="ts-caption">{caption}</span><h2>{heading}</h2></div>
    <span class="meta">{esc(profile["en"])}</span>
  </div>
  <p>{esc(lede)}</p>
  <div class="portfolio">{groups}</div>
  <div style="margin-top:2mm">
    <span class="ts-caption">Capability model · 核心能力</span>
    <div class="capability" style="margin-top:3mm">{caps}</div>
  </div>
  {page_foot(profile, 3, total, heading)}
</section>'''


def cjk(value):
    """Numbers stay in the mono face; a value written in Chinese goes back to the serif."""
    return ' data-long' if any('\u4e00' <= ch <= '\u9fff' for ch in value) else ''


def delta_strip(case):
    """Before and after, when the case states both. Two bars to scale plus the gain."""
    facts = {f['k']: f['v'] for f in case['facts']}
    pairs = [(k, k.replace('前', '后')) for k in facts if '前' in k and k.replace('前', '后') in facts]
    if not pairs:
        return ''
    before_key, after_key = pairs[0]
    import re as _re

    def number(text):
        found = _re.search(r'[\d.]+', text)
        return float(found.group()) if found else 0.0
    b, a = number(facts[before_key]), number(facts[after_key])
    if not b or not a:
        return ''
    wide = max(b, a)
    gain = (a - b) / b * 100
    return (f'<div class="delta">'
            f'<span class="side"><span class="k">{esc(before_key)}</span><span class="v">{esc(facts[before_key])}</span></span>'
            f'<span class="bars"><i style="width:{b / wide * 100:.0f}%"></i><i class="after" style="width:{a / wide * 100:.0f}%"></i></span>'
            f'<span class="side" style="text-align:right"><span class="k">{esc(after_key)}</span><span class="v">{esc(facts[after_key])}</span>'
            f'<span class="gain">+{gain:.0f}%</span></span></div>')


def page_case(profile, case, data, no, total):
    delta = delta_strip(case)
    names = {c['id']: c['title'] for c in profile['capabilities']}
    caps = ''.join(f'<span class="ts-badge ts-badge-outline">{esc(names[c])}</span>' for c in case.get('capabilities', []))
    src = data['sources'][profile['source']]
    facts = ''.join(f'<div><span class="k">{esc(f["k"])}</span><span class="v">{esc(f["v"])}</span></div>'
                    for f in case['facts'])
    results = ''.join(
        f'<div class="r"><span class="m">{esc(r["metric"])}<small>{esc(r["window"])} · {esc(r["grade"])}</small></span>'
        f'<span class="v"{cjk(r["value"])}>{esc(r["value"])}</span></div>'
        for r in case['results'])
    return f'''<section class="page" id="{esc(case["id"])}">
  <div class="page-head">
    <div><span class="ts-caption">Selected case · 选摘案例</span><h2>{esc(case["title"])}</h2></div>
    <span class="meta">{esc(profile["en"])}</span>
  </div>
  <div class="facts">{facts}</div>
  {delta}
  <div class="cards-2 fill">
    <div class="block"><span class="ts-caption">Product strategy · 产品策略</span><p>{esc(case["strategy"])}</p></div>
    <div class="block"><span class="ts-caption">Business result · 经营结果</span><div class="results">{results}</div></div>
  </div>
  <div class="case-foot">
    <div><span class="ts-caption">Capabilities exercised · 本案涉及能力</span><div class="strip">{caps}</div></div>
    <p class="note">数字出处：{esc(src["label"])}（{esc(src["kind"])}，{esc(src["date"])}），等级 {esc(src["grade"])}。口径与全部条目见第 {total} 页。</p>
  </div>
  {page_foot(profile, no, total, case["title"])}
</section>'''


def page_sources(profile, data, no, total):
    rows = ''
    for entry in numbers(profile, unique=True):
        src = data['sources'][entry['source']]
        label = entry.get('metric') or entry.get('zh') or entry.get('title', '')
        value = entry.get('value') or entry.get('scale') or ''
        window = entry.get('window') or entry.get('note') or entry.get('region') or ''
        cat = data['categories'][entry.get('type', 'case' if 'metric' in entry else 'figure')]['zh'] \
            if entry.get('type') in data['categories'] else data['categories']['case']['zh']
        rows += (f'<tr><td>{esc(label)}</td><td class="ts-mono">{esc(value)}</td><td>{esc(window)}</td>'
                 f'<td>{esc(cat)}</td><td><span class="grade">{esc(entry["grade"])}</span></td>'
                 f'<td>{esc(src["label"])} · {esc(src["kind"])} · {esc(src["date"])}</td></tr>')
    grades = ''.join(f'<div><b class="ts-mono">{esc(k)}</b> {esc(v)}</div>' for k, v in data['grades'].items())
    items = ''.join(f'<li>{esc(i["text"])}</li>' for i in data['open_items']
                    if i['profile'] in ('*', profile['id']))
    edits = ''.join(f'<li>「{esc(e["from"])}」改为「{esc(e["to"])}」—— {esc(e["why"])}</li>'
                    for e in data['lexicon_edits'] if e['profile'] == profile['id'])
    return f'''<section class="page" id="sources">
  <div class="page-head">
    <div><span class="ts-caption">Sources and definitions</span><h2>数据出处与口径</h2></div>
    <span class="meta">{esc(profile["en"])}</span>
  </div>
  <p style="font-size:9.5pt">本页列出前面每一个数字的口径、类别、证据等级与出处。</p>
  <div class="grades">{grades}</div>
  <table class="ts-table-ledger sourcetable">
    <thead><tr><th>指标</th><th>数值</th><th>口径 / 窗口</th><th>类别</th><th>等级</th><th>出处</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
  <div class="cards-2">
    <div class="block"><span class="ts-caption">Open items · 待核</span><ul class="notes">{items}</ul></div>
    {'<div class="block" data-lexicon-note><span class="ts-caption">Lexicon edits · 语汇调整</span><ul class="notes">' + edits + '</ul></div>' if edits else '<div></div>'}
  </div>
  {page_foot(profile, no, total, "出处与口径")}
</section>'''


def switchbar(profile):
    boxes = ''.join(
        f'<label class="ts-tag"><input type="checkbox" value="{esc(t["zh"])}"{" checked" if t["show"] else ""}> {esc(t["zh"])}</label>'
        for t in profile['titles_aux'])
    return f'''<div class="ts-container">
  <div class="switchbar">
    <span class="ts-caption">辅助职务 · 最多显示 3 个</span>
    {boxes}
    <span class="hint">此处为预览；正式显示以 people/profiles.json 中的 show 字段为准，改后运行 python3 scripts/build_profiles.py。</span>
    <span class="over" hidden>已超过 3 个</span>
  </div>
</div>'''


def render_full(profile, data):
    cases = profile['cases']
    total = 4 + len(cases)
    pages = [cover(profile, data, total), page_profile(profile, total), page_portfolio(profile, total)]
    pages += [page_case(profile, c, data, 4 + i, total) for i, c in enumerate(cases)]
    pages.append(page_sources(profile, data, total, total))
    body = '\n'.join(pages)
    title = f'{profile["name"]} {profile["en"]} · {profile["title_main"]} · 完整版 · 侍天 TIANSIGHT'
    return f'''{head(title)}
{shell_head(profile, "完整版 Full", f"profile-{profile['id']}-1p.html", "一页版")}
{switchbar(profile)}
<main id="top" class="pages">
{body}
</main>
<script src="profile.js"></script>
</body>
</html>
'''


def render_onepage(profile, data):
    aux = [t for t in profile['titles_aux'] if t['show']][:MAX_AUX]
    aux_html = ''.join(f'<span>{esc(t["zh"])}</span>' for t in aux)
    figs = ''.join(
        f'<div class="fig"><span class="v">{esc(f["value"])}'
        + (f'<small>{esc(f["unit"])}</small>' if f.get('unit') else '')
        + f'</span><span class="l">{esc(f["label"])}</span><span class="n">{esc(f["zh"])}</span></div>'
        for f in profile['figures'])
    photo = root / 'people' / profile['photo']
    portrait = (f'<img src="{esc(profile["photo"])}" alt="{esc(profile["name"])}">' if photo.is_file()
                else '<span class="ts-caption" style="text-align:center;padding:3mm">肖像待补</span>')
    caps = ''.join(f'<span class="ts-badge ts-badge-outline">{esc(c["title"])}</span>' for c in profile['capabilities'])
    cases = ''
    for case in [c for c in profile['cases'] if 'onepage' in c['show_in']]:
        meta = ' · '.join(f['v'] for f in case['facts'][:3])
        items = ''.join(f'<li><span>{esc(r["metric"])}</span><b>{esc(r["value"])}</b></li>' for r in case['results'][:3])
        cases += (f'<div class="c"><h2>{esc(case["title"])}</h2><span class="meta">{esc(meta)}</span>'
                  f'<ul>{items}</ul></div>')
    if profile.get('brands'):
        coverage = '服务品牌：' + '、'.join(b['group'] for b in profile['brands'])
    else:
        coverage = '服务覆盖：' + '、'.join(s['group'] for s in profile['services'])
    src = data['sources'][profile['source']]
    title = f'{profile["name"]} {profile["en"]} · {profile["title_main"]} · 一页版 · 侍天 TIANSIGHT'
    return f'''{head(title)}
{shell_head(profile, "一页版 One page", f"profile-{profile['id']}.html", "完整版")}
<main id="top" class="pages">
<section class="page onepage" id="onepage">
  <div class="page-head">
    <div><span class="ts-caption">侍天 Tiansight ｜ A Member of the Table AI Alliance</span><span class="domain-line">{esc(profile["domain"])}</span></div>
    <span class="meta">{esc(data["version"])} · {esc(data["issued"])}</span>
  </div>
  <div class="hero">
    <div class="portrait">{portrait}</div>
    <div>
      <h1>{esc(profile["name"])}<span class="ts-caption" style="margin-left:3mm">{esc(profile["en"])}</span></h1>
      <div class="titles" style="margin-top:2mm">
        <span class="main">{esc(profile["title_main"])}</span>
        <div class="aux">{aux_html}</div>
      </div>
      <p style="margin-top:3mm">{esc(profile["lede"])}</p>
      <p class="ts-latin" lang="en" style="margin-top:2mm;color:var(--gold);font-size:9.5pt"><em>「{esc(profile["quote"])}」</em></p>
    </div>
    <div class="figures">{figs}</div>
  </div>
  <div class="page-rule"></div>
  <p style="font-size:9pt">{esc(profile["summary"][0])}</p>
  <div>
    <span class="ts-caption">Capability model · 核心能力</span>
    <div class="strip" style="margin-top:2mm">{caps}</div>
  </div>
  <div>
    <span class="ts-caption">Selected cases · 选摘案例</span>
    <div class="cases" style="margin-top:2.5mm">{cases}</div>
  </div>
  <div>
    <span class="ts-caption">Coverage · 覆盖</span>
    <p style="font-size:9pt;margin-top:1.5mm">{esc(coverage)}</p>
  </div>
  <p class="foot-note">数字口径与出处见完整版第 {4 + len(profile["cases"])} 页。本页数字来源：{esc(src["label"])}（{esc(src["kind"])}，{esc(src["date"])}），等级 {esc(src["grade"])}，客户可见前请逐条确认。</p>
  {page_foot(profile, 1, 1, profile["domain_zh"])}
</section>
</main>
</body>
</html>
'''


def render_index(data):
    cards = ''
    for profile in data['profiles']:
        aux = ' · '.join(t['zh'] for t in profile['titles_aux'] if t['show'])
        counts = {}
        for key in ('figures', 'principles', 'capabilities', 'brands', 'services', 'roles', 'education', 'trainings', 'cases'):
            for entry in profile.get(key, []):
                cat = entry.get('type', 'case')
                counts[cat] = counts.get(cat, 0) + 1
        chips = ''.join(
            f'<span class="ts-badge ts-badge-outline">{esc(data["categories"][c]["zh"])} {n}</span>'
            for c, n in sorted(counts.items()))
        cards += f'''<article class="ts-card" data-index="{esc(profile["order"])}">
      <span class="ts-caption">{esc(profile["domain"])}</span>
      <h2 class="ts-card-title">{esc(profile["name"])} {esc(profile["en"])}</h2>
      <p class="ts-small"><b>{esc(profile["title_main"])}</b><br>{esc(aux)}</p>
      <p class="ts-small ts-muted">{esc(profile["lede"])}</p>
      <div class="chips" style="margin-top:var(--space-3)">{chips}</div>
      <div class="links" style="margin-top:var(--space-4)">
        <a href="profile-{esc(profile["id"])}.html">完整版</a>
        <a href="profile-{esc(profile["id"])}-1p.html">一页版</a>
      </div>
    </article>'''
    vocab = ''.join(
        f'<tr><td class="ts-mono">{esc(key)}</td><td>{esc(v["zh"])}</td><td>{esc(v["en"])}</td><td class="ts-small ts-muted">{esc(v["note"])}</td></tr>'
        for key, v in data['categories'].items())
    grades = ''.join(f'<tr><td class="ts-mono">{esc(k)}</td><td>{esc(v)}</td></tr>' for k, v in data['grades'].items())
    items = ''.join(f'<li>{esc(i["text"])}<span class="ts-small ts-muted">（{esc("全部" if i["profile"] == "*" else i["profile"])}）</span></li>'
                    for i in data['open_items'])
    return f'''{head('联合创始人履历库 · 侍天 TIANSIGHT')}
<main id="top" class="ts-container ts-section">
  <div class="ts-heading">
    <span class="ts-caption">Co-founder profiles · {esc(data["version"])} · {esc(data["issued"])}</span>
    <h1>联合创始人履历库</h1>
    <p class="ts-sub">一份 <code>people/profiles.json</code> 驱动两种版本：完整版七页、一页版一页。每条经历归入下方类别，每个数字带出处与证据等级。主职务统一为「侍天联合创始人」，辅助职务在数据中开关，最多显示三个。</p>
  </div>
  <div class="profile-cards" style="margin-top:var(--space-7)">{cards}</div>
  <div style="margin-top:var(--space-8)">
    <span class="ts-caption">Category vocabulary · 数据类型</span>
    <div class="ts-scroll-x" style="margin-top:var(--space-3)">
      <table class="ts-table-ledger">
        <thead><tr><th>键</th><th>类别</th><th>English</th><th>说明</th></tr></thead>
        <tbody>{vocab}</tbody>
      </table>
    </div>
  </div>
  <div style="margin-top:var(--space-7)">
    <span class="ts-caption">Evidence grades · 证据等级</span>
    <div class="ts-scroll-x" style="margin-top:var(--space-3)">
      <table class="ts-table-ledger">
        <thead><tr><th>等级</th><th>含义</th></tr></thead>
        <tbody>{grades}</tbody>
      </table>
    </div>
  </div>
  <div class="ts-notice ts-notice-warn" style="margin-top:var(--space-7)">
    <span class="ts-caption">待核</span>
    <div><ul style="margin:0;padding-left:1.2em">{items}</ul></div>
  </div>
  <p class="ts-small ts-muted" style="margin-top:var(--space-6)">生成命令：<code>python3 scripts/build_profiles.py</code>。数据源：<code>people/profiles.json</code>。</p>
</main>
</body>
</html>
'''


def outputs(data):
    files = {root / 'people' / 'profiles.html': render_index(data)}
    for profile in data['profiles']:
        files[root / 'people' / f'profile-{profile["id"]}.html'] = render_full(profile, data)
        files[root / 'people' / f'profile-{profile["id"]}-1p.html'] = render_onepage(profile, data)
    return files


def main(check=False):
    data = load()
    problems = validate(data)
    if problems:
        print('FAIL: people/profiles.json')
        for p in problems:
            print(' -', p)
        return 1
    files = outputs(data)
    stale = [p for p, text in files.items() if not p.is_file() or p.read_text(encoding='utf-8') != text]
    if check:
        if stale:
            print('stale: ' + ', '.join(sorted(p.relative_to(root).as_posix() for p in stale))
                  + ' — run python3 scripts/build_profiles.py')
            return 1
        print(f'profiles are up to date ({len(files)} pages)')
        return 0
    for path, text in files.items():
        path.write_text(text, encoding='utf-8')
    print(f'wrote {len(files)} pages: ' + ', '.join(sorted(p.name for p in files)))
    return 0


if __name__ == '__main__':
    sys.exit(main('--check' in sys.argv))
