/* Export the co-founder profile pages: PDFs and self-contained single-file HTML.
 *
 *   node scripts/export_profiles.mjs             # people/export/profile-<id>.pdf, -1p.pdf, .single.html
 *
 * PDFs come from headless Chromium with the page's own @page A4 rules. The single-file HTML inlines
 * the four brand stylesheets, profile.css, profile-edit.js and the mark as a data URI, so one file
 * opens from mail, a phone or another system with its backstage intact. people/export/ is ignored
 * by git; run this when a deliverable is needed. Requires the global Playwright install.
 */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const globalRoot = execSync('npm root -g').toString().trim();
const { chromium } = await import(resolve(globalRoot, 'playwright/index.mjs'));
const out = resolve(root, 'people/export');
mkdirSync(out, { recursive: true });

const data = JSON.parse(readFileSync(resolve(root, 'people/profiles.json'), 'utf8'));
const pages = [];
for (const p of data.profiles) pages.push(`profile-${p.id}.html`, `profile-${p.id}-1p.html`);

function inline(html) {
  const css = (rel) => readFileSync(resolve(root, 'people', rel), 'utf8');
  const logo = 'data:image/png;base64,' + readFileSync(resolve(root, 'brand/logo.png')).toString('base64');
  let styles = '';
  html = html.replace(/<link rel="stylesheet" href="([^"]+)">\n?/g, (_, href) => {
    styles += `\n/* ── ${href} ── */\n` + css(href).replace(/url\("fonts\//g, 'url("../brand/fonts/');
    return '';
  });
  html = html.replace('</head>', `<style>${styles}\n</style>\n</head>`);
  html = html.replace(/<script src="profile-edit\.js"><\/script>/, () => `<script>\n${css('profile-edit.js')}\n</script>`);
  html = html.replace(/\.\.\/brand\/logo\.png/g, logo);
  html = html.replace('<!-- Generated by', '<!-- Single-file export by scripts/export_profiles.mjs. Generated by');
  return html;
}

const browser = await chromium.launch();
const written = [];
for (const file of pages) {
  const pg = await browser.newPage();
  await pg.goto('file://' + resolve(root, 'people', file));
  await pg.waitForTimeout(300);
  const pdf = resolve(out, file.replace('.html', '.pdf'));
  await pg.pdf({ path: pdf, format: 'A4', printBackground: true, preferCSSPageSize: true, margin: { top: 0, right: 0, bottom: 0, left: 0 } });
  written.push(pdf);
  await pg.close();
  const single = resolve(out, file.replace('.html', '.single.html'));
  writeFileSync(single, inline(readFileSync(resolve(root, 'people', file), 'utf8')));
  written.push(single);
}
await browser.close();
console.log('wrote ' + written.length + ' files to people/export/:\n  ' + written.map((f) => f.replace(root + '/', '')).join('\n  '));
